#!/bin/bash
#SBATCH --ntasks=8
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=1GB
#SBATCH --time=01:00:00
#SBATCH --account=irahbari_1339
#SBATCH --reservation=focex

#module purge
#module load usc/11.3.0
#module load python/3.11.3
#module load pmix/4.2.4 

mpirun -n $SLURM_NTASKS python3 mpi-trapez.py
#mpirun -n $SLURM_NTASKS python3 mpi-reduce-trap.py
#srun --mpi=pmix_v2 -n $SLURM_NTASKS python3 mpi-trapez.py
