#!/bin/bash
#SBATCH --ntasks=8
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=1GB
#SBATCH --time=00:10:00
#SBATCH --account=irahbari_1339

module purge
#module load gcc/11.3.0
#module load openblas/0.3.21
#module load openmpi/4.1.4
module load usc
#module load python/3.11.3
#module load pmix/4.2.4 

mpirun -n $SLURM_NTASKS python3 hello_mpi.py
#srun --mpi=pmix_v2 -n $SLURM_NTASKS python3 hello_mpi.py
